# Generated by Django 4.2.1 on 2023-05-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField(verbose_name='Original URL')),
                ('shortened_url', models.CharField(unique=True, verbose_name='Shortened URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Createt At')),
                ('times_followed', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
